#pragma once

#define DEFAULT_VOLUME 1

#include <process.h>

namespace Client
{
	enum LEVEL { 
		LEVEL_STATIC, 
		LEVEL_LOADING, 
		LEVEL_LOGO, 
		LEVEL_OFFICE_1F, 
		LEVEL_OFFICE_2F, 
		LEVEL_OFFICE_BOSS, 
		LEVEL_DOGIMAZO, 
		LEVEL_DOGIMAZO_STAIRS,
		LEVEL_DOGIMAZO_LOBBY, 
		LEVEL_DOGIMAZO_BOSS, 
		LEVEL_STREET,
		LEVEL_CARCHASE,
		LEVEL_KARAOKE,
		LEVEL_TUTORIAL,
		LEVEL_NISHIKIWALK,
		LEVEL_TOKOSTREET,
		LEVEL_KARAOKE_START,
		LEVEL_KARAOKE_END,
		LEVEL_TEST, 
		LEVEL_END };

	enum STAGE { 
		STAGE_OFFICE_1F, 
		STAGE_OFFICE_2F, 
		STAGE_OFFICE_BOSS, 
		STAGE_DOGIMAZO, 
		STAGE_DOGIMAZO_STAIRS, 
		STAGE_DOGIMAZO_LOBBY, 
		STAGE_DOGIMAZO_BOSS, 
		STAGE_STREET,
		STAGE_ROADWAY,
		STAGE_KARAOKE,
		STAGE_TUTORIAL,
		STAGE_NISHIKIWALK,
		STAGE_KARAOKE_START,
		STAGE_KARAOKE_END,
		STAGE_TOKOSTREET,
		STAGE_OFFICE_BOSS_END,
		STAGE_END };

	enum CAMERA { CAMERA_DEBUG, CAMERA_CINEMACHINE, CAMERA_PLAYER, CAMERA_CUTSCENE, CAMERA_CARCHASE, CAMERA_MAP, CAMERA_END };
	enum TRIGGER_LEVEL { MONSTER_TRIGGER_0, MONSTER_TRIGGER_1, MONSTER_TRIGGER_END };

	const unsigned int		g_iWinSizeX = 1280;
	const unsigned int		g_iWinSizeY = 720;
}

extern HINSTANCE g_hInst;
extern HWND g_hWnd;

using namespace Client;

